### ISSUE TITLE
aio -v command suggested by Getting Started documentation does not exist

### ISSUE THREAD

**Issue by tvhees** [AdobeDocs/app-builder#280]
### Expected Behaviour
Running `aio -v` as suggested by the documentation should display the currently installed CLI version.

### Actual Behaviour
The following warning is printed:

``` 
 ›   Warning: -v is not a aio command.
Did you mean rt? [y/n]: 
```

#### Steps to Reproduce
Install cli: `npm install -g @adobe/aio-cli`
Run command: `aio -v`

#### Platform and Version
Ubuntu 20.04.5 LTS
Node v16.14.2
aio-cli v9.1.1

**Comment by shazron** [comment]
Fixed in aio-cli@9.4.1 https://github.com/adobe/aio-cli/pull/525
